const GET_ALL_BREEDS = 'GET_ALL_BREEDS';
const GET_BREED_DETAIL = 'GET_BREED_DETAIL';
const GET_BREED_SEARCH = 'GET_BREED_SEARCH';
const GET_ALL_TEMPERAMENTS = 'GET_ALL_TEMPERAMENTS;'
const CREATE_BREED = 'CREAT_BREED';
const AZ_ALPHABETIC_ORDER = 'AZ_ALPHABETIC_ORDER';
const ZA_ALPHABETIC_ORDER = 'ZA_ALPHABETIC_ORDER';
const MAX_HIGHER_WEIGHT_ORDER = 'MAX_HIGHER_WEIGHT_ORDER';
const MIN_HIGHER_WEIGHT_ORDER = 'MIN_HIGHER_WEIGHT_ORDER';
const MAX_LOWER_WEIGHT_ORDER = 'MAX_LOWER_WEIGHT_ORDER';
const MIN_LOWER_WEIGHT_ORDER = 'MIN_LOWER_WEIGHT_ORDER';
const API_BREEDS_FILTER = 'API_BREEDS_FILTER';
const DB_BREEDS_FILTER = 'DB_BREEDS_FILTER';

export {
    GET_ALL_BREEDS,
    GET_BREED_DETAIL,
    GET_BREED_SEARCH,
    GET_ALL_TEMPERAMENTS,
    CREATE_BREED,
    AZ_ALPHABETIC_ORDER,
    ZA_ALPHABETIC_ORDER,
    MAX_HIGHER_WEIGHT_ORDER,
    MIN_HIGHER_WEIGHT_ORDER,
    MAX_LOWER_WEIGHT_ORDER,
    MIN_LOWER_WEIGHT_ORDER,
    API_BREEDS_FILTER,
    DB_BREEDS_FILTER
};