const GET_ALL_BREEDS = 'GET_ALL_BREEDS';
const GET_BREED_DETAIL = 'GET_BREED_DETAIL';
const GET_BREED_SEARCH = 'GET_BREED_SEARCH';
const GET_ALL_TEMPERAMENTS = 'GET_ALL_TEMPERAMENTS;'
const CREATE_BREED = 'CREAT_BREED';

export {
    GET_ALL_BREEDS,
    GET_BREED_DETAIL,
    GET_BREED_SEARCH,
    GET_ALL_TEMPERAMENTS,
    CREATE_BREED
};